### ISSUE TITLE
Setup Code Coverage

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/GI-Weekly-Material-Tracker#585]
## Describe new feature below
Setup the code coverage for this repository once its ready.

Existing GitLab CI Codes to port over to GitHub Actions
```yaml
Code Coverage:
 image: itachi1706/flutter-alpine-android:web
 stage: test
 allow_failure: true
 variables:
   APP_BUILD_VER: qa
   APP_TYPE: QA
 before_script:
   - flutter doctor -v
   - apk add --no-cache make perl
   - git clone https://github.com/linux-test-project/lcov.git
   - cd lcov
   - make install
 script:
   # Allow failure for now as we are not really using it tbh
   - flutter test --coverage || true
   - lcov --list coverage/lcov.info
   - genhtml -o coverage coverage/lcov.info
 coverage:
   '/\s*lines\.*:\s*([\d\.]+%)/'
 artifacts:
   paths:
     - coverage/
 needs: []
```
